### ISSUE TITLE
[TSK-280] A guide on how to run scrapers locally

### ISSUE THREAD

**Issue by maany** [dream-aim-deliver/planckster-docs#17] opened 2024-08-03 00:20 UTC
Create a guide detailing how you can set up Sentinel Scraper locally

**Comment by Deeptikandhol10** [comment] 2024-08-05 06:11
@Rahul-7131, what is the status of this activity?

**Comment by Rahul-7131** [comment] 2024-08-05 07:08
Working on it, if everything goes as intended most probably I'll complete it by tonight or tomorrow

**Comment by Deeptikandhol10** [comment] 2024-08-05 07:24
Perfect.

**Comment by Rahul-7131** [comment] 2024-08-05 20:23
Done with the documentation for setup of sentinel scraper, let me know if any further additions are needed to this.

**Comment by Deeptikandhol10** [comment] 2024-08-06 06:31
@maany could you review it ?

**Comment by Deeptikandhol10** [comment] 2024-08-07 15:20
@maany  could you review it?

**Comment by ydamit** [comment] 2024-08-07 20:37
It looks like this same set of edits in [this PR](https://github.com/dream-aim-deliver/planckster-docs/pull/22) is being merged in the [Guide for running Kubeflow pipelines PR](https://github.com/dream-aim-deliver/planckster-docs/pull/25). Maybe we can just close this PR in favor of that one (where I've added a couple suggestions)?

**Comment by Rahul-7131** [comment] 2024-08-08 12:53
yeah It seems I have merged two Issues into one PR, I'll close this PR and link that one instead

**Comment by Deeptikandhol10** [comment] 2024-08-09 07:19
@Rahul-7131 . what's the status of this activity ? Done?

**Comment by Rahul-7131** [comment] 2024-08-09 07:26
Yes @Deeptikandhol10 this is done

**Closed** 2024-08-09 12:16 UTC
Labels: documentation
